### ISSUE TITLE
[Meta-issue] Compatibility with GUID Partition Table(GPT)

### ISSUE THREAD

**Issue by Lin-Buo-Ren** [slacka/WoeUSB#75]
## Problem ##
Currently WinUSB only knows about MBR partitioning scheme and will fail on disks with GUID Partition Table.

## Solution ##
* [x] Investigate whether it's possible to properly boot & use Windows installation media using BIOS-GPT booting method.
* [ ] Implement logic to identify whether GUID Partition Table should be used in `--format` mode, and using it when it's preferred(e.g. >2TB disk)
* [ ] Implement logic to identify which partitioning scheme the target disk is currently using in `--install` mode; if GUID Partition Table is used, install GRUB in a way that it can be booted using IBM PC-XT Compatible/Legacy booting (only if Windows bootable media works happily with this configuration)

**Comment by Lin-Buo-Ren** [comment]
It is verified that Windows won't boot if disk is using GUID Partition Table and using Legacy PC boot method, closing...
